import React, { useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Canvas, useFrame } from '@react-three/fiber';
import { Environment, ContactShadows, Float, OrbitControls } from '@react-three/drei';
import './styles.css';

const cars = [
  { id:'aether', name:'Aether R', type:'Grand Tourer', price:'142 900 €', power:'620 ch', zero:'3,4 s', speed:'320 km/h', color:'#aab2bc', accent:'#53c6ff' },
  { id:'noctis', name:'Noctis RS', type:'Performance Coupé', price:'118 500 €', power:'540 ch', zero:'3,8 s', speed:'305 km/h', color:'#27313e', accent:'#7a9cff' },
  { id:'velum', name:'Velum S', type:'Electric Sport', price:'96 800 €', power:'510 ch', zero:'3,9 s', speed:'280 km/h', color:'#e8e6e1', accent:'#65e2ff' }
];

function CarModel({ color='#aab2bc' }) {
  const ref=useRef();
  useFrame((state)=>{ if(ref.current) ref.current.rotation.y = state.pointer.x * .34; });
  return <group ref={ref} rotation={[0,-.28,0]}>
    <mesh position={[0,.38,0]} castShadow><boxGeometry args={[3.55,.48,1.45]}/><meshStandardMaterial color={color} metalness={.9} roughness={.2}/></mesh>
    <mesh position={[.18,.78,0]} castShadow><boxGeometry args={[1.72,.48,1.18]}/><meshStandardMaterial color={color} metalness={.85} roughness={.18}/></mesh>
    <mesh position={[.18,.82,0]}><boxGeometry args={[1.35,.3,1.06]}/><meshStandardMaterial color="#101720" metalness={.35} roughness={.1}/></mesh>
    {[[-1.15,.15,.77], [1.15,.15,.77],[-1.15,.15,-.77],[1.15,.15,-.77]].map((p,i)=><mesh key={i} position={p} rotation={[Math.PI/2,0,0]} castShadow><cylinderGeometry args={[.38,.38,.22,32]}/><meshStandardMaterial color="#080a0e" metalness={.8} roughness={.24}/></mesh>)}
    <mesh position={[1.79,.43,0]}><boxGeometry args={[.05,.07,1.05]}/><meshStandardMaterial color="#74d9ff" emissive="#2aaeff" emissiveIntensity={4}/></mesh>
    <mesh position={[-1.79,.43,0]}><boxGeometry args={[.05,.07,1.05]}/><meshStandardMaterial color="#ff3b6b" emissive="#ff164e" emissiveIntensity={2}/></mesh>
  </group>
}
function CarCanvas({small=false}) { return <div className={small?'car-canvas small':'car-canvas'}><Canvas shadows camera={{position:[4,2.4,5],fov:38}}><ambientLight intensity={.35}/><spotLight position={[2,5,3]} intensity={80} angle={.35} penumbra={1} castShadow/><pointLight position={[-4,1,-2]} color="#168dff" intensity={20}/><Float speed={1} rotationIntensity={.08} floatIntensity={.18}><CarModel/></Float><ContactShadows position={[0,-.15,0]} opacity={.55} scale={7} blur={2.5}/><Environment preset="city"/><OrbitControls enableZoom={false} enablePan={false} minPolarAngle={1.1} maxPolarAngle={1.65}/></Canvas></div> }
function Header({page,setPage}) { return <header><button className="brand" onClick={()=>setPage('home')}><span>AL</span> AUTOLUX</button><nav><button onClick={()=>setPage('home')} className={page==='home'?'active':''}>Accueil</button><button onClick={()=>setPage('catalog')} className={page==='catalog'?'active':''}>Modèles</button><button onClick={()=>setPage('contact')} className={page==='contact'?'active':''}>Nous trouver</button></nav><button className="outline" onClick={()=>setPage('contact')}>Prendre rendez-vous <b>↗</b></button></header> }
function Home({setPage}) { return <><section className="hero"><div className="hero-copy"><p className="eyebrow">AUTOLUX / COLLECTION 2025</p><h1>Drive<br/><em>beyond.</em></h1><p className="lead">L'ingénierie de la performance, sculptée pour ceux qui refusent les compromis.</p><div className="actions"><button className="primary" onClick={()=>setPage('catalog')}>Explorer la collection <b>↗</b></button><button className="textbtn" onClick={()=>setPage('contact')}>Réserver un essai <span>→</span></button></div></div><div className="hero-car"><div className="halo"/><CarCanvas/><div className="hint">↔ <span>Faites glisser pour explorer</span></div></div><div className="hero-meta"><span>01 — 03</span><div className="progress"><i/></div><span>Une nouvelle perspective</span></div></section><section className="intro"><p className="eyebrow">L'EXCELLENCE EN MOUVEMENT</p><h2>Chaque ligne a une raison.<br/><span>Chaque trajet, une signature.</span></h2><p className="muted">AutoLux sélectionne des automobiles d'exception et compose avec vous une expérience aussi singulière que votre conduite.</p></section></> }
function Catalog({setPage}) { return <main className="page"><div className="page-title"><div><p className="eyebrow">LA COLLECTION AUTOLUX</p><h1>Choisissez votre<br/><em>prochaine émotion.</em></h1></div><p className="muted">03 modèles · édition limitée<br/>Disponibles à l'essai en showroom</p></div><div className="catalog">{cars.map((car,i)=><article className="car-card" key={car.id} onClick={()=>setPage('detail')}><div className="card-number">0{i+1}</div><CarCanvas small/><div className="card-copy"><p className="eyebrow">{car.type}</p><h2>{car.name}</h2><div><span>{car.price}</span><button>Découvrir ↗</button></div></div></article>)}</div></main> }
function Detail({setPage}) { const car=cars[0]; return <main className="page detail"><button className="back" onClick={()=>setPage('catalog')}>← Retour à la collection</button><div className="detail-grid"><div><p className="eyebrow">GRAND TOURER / AETHER SERIES</p><h1>Aether <em>R</em></h1><p className="lead">Une présence sculpturale. Une accélération qui redéfinit l'horizon.</p><CarCanvas/></div><div className="spec-panel"><p className="eyebrow">PERFORMANCES</p><div className="specs"><div><strong>{car.power}</strong><small>Puissance</small></div><div><strong>{car.zero}</strong><small>0 — 100 km/h</small></div><div><strong>{car.speed}</strong><small>Vitesse max.</small></div><div><strong>V8</strong><small>Moteur biturbo</small></div></div><div className="price">À partir de <strong>{car.price}</strong></div><button className="primary wide" onClick={()=>setPage('contact')}>Réserver un essai <b>↗</b></button><p className="fine">Personnalisation, financement et livraison sur mesure disponibles.</p></div></div></main> }
function Contact() { const [sent,setSent]=useState(false); return <main className="page contact"><div className="contact-heading"><p className="eyebrow">L'EXPÉRIENCE AUTOLUX</p><h1>Votre prochain<br/><em>départ commence ici.</em></h1><p className="muted">Venez rencontrer nos modèles dans un cadre privé et prendre le temps de choisir celui qui vous ressemble.</p><div className="contact-info"><span>01 84 80 20 25</span><span>showroom@autolux.fr</span><span>Paris · Genève · Monaco</span></div></div><form onSubmit={e=>{e.preventDefault();setSent(true)}}><p className="eyebrow">RÉSERVER UN ESSAI</p>{sent?<div className="success">Merci. Notre équipe vous recontactera sous 24 heures.</div>:<><label>Nom complet<input required placeholder="Jean Dupont"/></label><label>Adresse email<input required type="email" placeholder="jean@exemple.fr"/></label><label>Modèle souhaité<select><option>Aether R</option><option>Noctis RS</option><option>Velum S</option></select></label><label>Votre message<textarea placeholder="Parlez-nous de votre projet..."/></label><button className="primary wide">Envoyer la demande <b>↗</b></button></>}</form></main> }
function App(){const [page,setPage]=useState('home');return <><Header page={page} setPage={setPage}/>{page==='home'?<Home setPage={setPage}/>:page==='catalog'?<Catalog setPage={setPage}/>:page==='detail'?<Detail setPage={setPage}/>:<Contact/>}<footer><span>© 2025 AUTOLUX</span><span>Instagram&nbsp;&nbsp; · &nbsp;&nbsp;LinkedIn</span><span>Scroll to explore ↘</span></footer></>};

createRoot(document.getElementById('root')).render(<App/>);